{% set name = "keras-tuner" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6befd25ee81476e6207d8ca7ed7dc674b8194437cfa0b127294cd00da905ff22

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - Ipython
    - kt-legacy
    - numpy
    - packaging
    - requests
    - scikit-learn
    - scipy
    - tensorboard
    - keras-core
    - protobuf


test:
  imports:
    - keras_tuner
    - keras_tuner.applications
    - keras_tuner.engine
    - keras_tuner.oracles
    - keras_tuner.tuners
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/keras-team/keras-tuner
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hypertuner for Keras
  doc_url: https://keras-team.github.io/keras-tuner/
  dev_url: https://github.com/keras-team/keras-tuner

extra:
  recipe-maintainers:
    - anselmoo
    - oblute
    - rluria14
    - Tata17
    - mxr-conda
