{% set name = "keras-tuner" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b13300093a0b430d4794a207d1dcac0c46c72ff92cfeda44264fbc02612f17fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - Ipython
    - kt-legacy
    - numpy
    - packaging
    - requests
    - scikit-learn
    - scipy
    - tensorboard
    - tensorflow >=2.0
    - protobuf


test:
  imports:
    - keras_tuner
    - keras_tuner.applications
    - keras_tuner.distribute
    - keras_tuner.engine
    - keras_tuner.oracles
    - keras_tuner.protos
    - keras_tuner.tuners
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-tuner
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hypertuner for Keras
  doc_url: https://keras-team.github.io/keras-tuner/
  dev_url: https://github.com/keras-team/keras-tuner

extra:
  recipe-maintainers:
    - anselmoo
    - oblute
    - rluria14
    - Tata17
    - mxr-conda
