{% set name = "keras-tuner" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5864db0320ce61b2e11e4533a9775a9bf213dbee97720409327dc41c71d0b88b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorama
    - future
    - numpy
    - python >=3.6
    - requests
    - scikit-learn
    - scipy
    - tabulate
    - terminaltables
    - tqdm
    - tensorflow >=2.0
    - Ipython
    - packaging
    - tensorboard


test:
  imports:
    - keras_tuner
    - keras_tuner.applications
    - keras_tuner.distribute
    - keras_tuner.engine
    - keras_tuner.oracles
    - keras_tuner.protos
    - keras_tuner.tuners

about:
  home: https://github.com/keras-team/keras-tuner
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hypertuner for Keras
  doc_url: https://keras-team.github.io/keras-tuner/
  dev_url: https://github.com/keras-team/keras-tuner

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - Tata17
    - mxr-conda
