{% set name = "keras-tuner" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 929a7ff1b8eb73166f95dd1dea1e5d45018e4bd33800c4a890116bff4b28ccf1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorama
    - future
    - numpy
    - python >=3.6
    - requests
    - scikit-learn
    - scipy
    - tabulate
    - terminaltables
    - tqdm
    - tensorflow >=2.0

test:
  imports:
    - kerastuner
    - kerastuner.abstractions
    - kerastuner.applications
    - kerastuner.distribute
    - kerastuner.engine
    - kerastuner.oracles
    - kerastuner.protos
    - kerastuner.tuners

about:
  home: https://github.com/keras-team/keras-tuner
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hypertuner for Keras
  doc_url: https://keras-team.github.io/keras-tuner/
  dev_url: https://github.com/keras-team/keras-tuner

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - Tata17
